### ISSUE TITLE
what is the mapping of ODH features to the MOC deployment?

### ISSUE THREAD

**Issue by goern** [operate-first/odh-moc-support#14]
**Description**

Looking at ODH upstream, there is a lot of features included. https://github.com/operate-first/odh-moc-support/issues/6 shows there are differences wrt what gets deploys to MOC.

What feature set of what ODH release is deployed to MOC and how is that documented?

**Comment by goern** [comment]
can we document the decision analogue to https://github.com/opendatahub-io/odh-manifests/pull/224 ?

**Comment by durandom** [comment]
the plan is to deploy *all* features of ODH - as laid out in https://github.com/operate-first/odh/issues/10

**Comment by HumairAK** [comment]
This question looks answered, for further info you can see the readme [here](https://github.com/operate-first/odh-moc-support). Feel free to re open if there are more questions. Thanks!
