### ISSUE TITLE
Cannot authenticate on JH

### ISSUE THREAD

**Issue by pacospace** [operate-first/odh-moc-support#15]
**Describe the bug**
Logging with gmail on JH give authentication error

**To Reproduce**
1. Try logging with gmail on JH

**Expected behavior**
Logging in JH after authentication.

**Screenshots**
```
{"error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.",
```

**Additional context**

**Comment by durandom** [comment]
@hemajv can you have a look at this?

**Comment by pacospace** [comment]
> @hemajv can you have a look at this?

I think is related to the cluster mentioned in the chat.

**Comment by 4n4nd** [comment]
Yes. Unfortunately, the MOC openshift cluster is down right now.

**Comment by pacospace** [comment]
> Yes. Unfortunately, the MOC openshift cluster is down right now.

any updates on the JH? :)

**Comment by 4n4nd** [comment]
@pacospace It should be up and working. I'll close this issue for now, please feel free to reopen it in case it doesn't work.

**Comment by pacospace** [comment]
Thanks @4n4nd :rocket: :beers:
