### ISSUE TITLE
[TASK] Request for the cnv ceph cluster creds

### ISSUE THREAD

**Issue by harshad16** [operate-first/odh-moc-support#18]
**User story**
We thoth-devops, would like to update our gitops related manifest file with correct ceph credentials corresponding to the moc cnv cluster, so that we can have our deployment run successfully and smoothly in the cnv operate-first cluster.

**Additional context**
Thoth component needs/requires ceph credentials to establish a connection with the ceph component for data storage. 

**Acceptance Criteria**
- [ ] Provide ceph credentials like access-key and access-secret-key 

**Linked epics / issues**
Related-To: https://github.com/operate-first/odh-moc-support/issues/16

**Comment by 4n4nd** [comment]
@durandom do we have any updates on the Ceph instance for MOC?

**Comment by durandom** [comment]
@4n4nd please have a look at https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox 
If there's nothing in the `/docs` folder, create an issue and tag Lars and ping Lars in google chat.

**Comment by 4n4nd** [comment]
Created an issue https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/54

**Comment by 4n4nd** [comment]
@harshad16 I have pinged Lars about the access to the S3 API external to the cluster, but If you are planning to use it within the cluster, you can create a [ObjectBucketClaim](https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#app-pod) in a namespace

**Comment by harshad16** [comment]
Thanks @4n4nd  for providing the information and for opening [issue](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/54) , this [comment](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/54#note_460217132) has made it clear on how to use it.
