### ISSUE TITLE
How to create a Jupyterhub image and deploy it on ODH?

### ISSUE THREAD

**Issue by SankBad** [operate-first/odh-moc-support#2]
As a data scientist, I want to share my notebooks with others and receive feedback. To make the notebooks more visible, How can I create a Jupyterhub image and deploy it on ODH so that they are available in the JH dropdown?

Is there any documentation regarding this? 

Acceptance criteria - 

- [x]  Configuration file analysis project available in the drop-down for Jupyterhub images on ODH. 

- [ ]  Documentation on how to make JH images available on ODH

**Comment by 4n4nd** [comment]
@SankBad we are thinking of following the same structure that is used in [upstream ODH](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/additional).

We don't have any documentation yet. But you will have to add your imagestream to the [operate-first/odh](https://github.com/operate-first/odh/tree/master/kfdef/jupyterhub) repo for it to be added to the operate-first Jupyterhub instance.

**Comment by martinpovolny** [comment]
@SankBad : Let me try to help.

Do you have your own deployment of ODH somewhere? Your cluster or some cluster you have access to?

If you don't then you need one. There are guides for playing with your own instance of ODH here: 

https://github.com/operate-first/continuous-deployment/blob/master/docs/index.md

To make an existing image available on ODH, it needs to have an ImageStream created and there needs to be a label telling ODH to use that image.

In this comment, there's an example of such image stream: https://github.com/operate-first/continuous-deployment/issues/30#issuecomment-701298940

The important part is:
```
  labels:
    opendatahub.io/notebook-image: "true"
```

In the link that @4n4nd provided, there more examples.

If your image is not yet built, you can use "Thoth" to do it for you using a config file similar to this one:

Here's an example that goes together with the above example of an ImageStream:

https://github.com/aicoe-aiops/categorical-encoding/blob/master/.aicoe-ci.yaml

I am going to compile this into a nice guide and would be grateful for your testing of the process or improvement suggestions.

**Comment by martinpovolny** [comment]
I am adding here

### Steps to add your notebook repo to Thoth for building

### Enable the CI integration

To get image built by Thoth (in Tekton?) (not sure what is the right formulation here) and uploaded to quay.io (image registry) one needs to add the "aicoe-ci" app to the project:

![github-app-2020-11-06_10-36](https://user-images.githubusercontent.com/51095/98358752-7b565180-2027-11eb-9ae0-755e2e5290c1.png)

If your project is under the `aicoe-aiops` (and some other) GH orgs then this is already done on the org level and you don't need it.

### Setting up the image repository 

One needs to have a place to upload the built images. For that you need an account and a project on quay.io.

Again there already is https://quay.io/organization/aicoe so if your project is part of aicoe you can use that.

In Quay one needs to all access for the Thoth by creating a robot account with a push secret.

![quay-robot-1](https://user-images.githubusercontent.com/51095/98359302-4bf41480-2028-11eb-9e19-899e2314fe90.png)

There are pre-configured push secrets for various projects already. It's on the bottom of this page: https://github.com/AICoE/aicoe-ci#services-and-features . So if your project is in one of these, you can skip this step.

Then the robot account needs to have access the project that you want to use:

![quay-repo-settings-2020-11-06_10-31](https://user-images.githubusercontent.com/51095/98359563-bdcc5e00-2028-11eb-94cc-7c3ac2394ade.png)

And finally, you need to add the push secret to the Thoth. Copy the secret here: 

![quay-robot-2](https://user-images.githubusercontent.com/51095/98359649-d76da580-2028-11eb-9d94-b49b715a4483.png)

Send the secret (the whole yaml) to @harshad16 to have it added if you need to use a new push secret.


### Adding configuration file to your repo

I am in the process of creating a minimal working config here: https://github.com/martinpovolny/colaboratory/blob/master/.aicoe-ci.yaml 

** more text missing here **

### Triggering the build

Once you have this in your repo. You can trigger the build by doing a release. This is something that will be done for you automatically if you are using the whole Thoth toolset. But for minimal working setup, you can create a release manually.

![github-tag-2020-11-06_10-42](https://user-images.githubusercontent.com/51095/98360056-7abeba80-2029-11eb-8300-f9e1c90397cb.png)

![github-tag-2-2020-11-06_10-43](https://user-images.githubusercontent.com/51095/98360067-814d3200-2029-11eb-9ff0-2282fac372fd.png)

If you have done these steps correctly, Thoth will pick up your tag and run a image build for you.

## Checking and debugging the build

You can login to https://tekton-dashboard-openshift-pipelines.apps.ocp4.prod.psi.redhat.com/ and find your build by using the search field. Enter "project:<YOUR_REPO_NAME>".

![tekton-search-build-2020-11-06_10-40](https://user-images.githubusercontent.com/51095/98360266-cb361800-2029-11eb-9f38-7189d0873c08.png)

The part that in relevant for image building is under "tag-release-run". There may by other sections that are red, but if this part is green the image was build and pushed. You can also check that on Quay.io.

**Comment by SankBad** [comment]
Thanks, @martinpovolny and @4n4nd 
I will try this and let you know if facing any issues.

**Comment by martinpovolny** [comment]
@sankBad: this is still a work in progress from my side. Do not hurry, unless you are in a hurry.

**Comment by SankBad** [comment]
Ohk, the work is not urgent, I will wait

**Comment by harshad16** [comment]
@martinpovolny  that's greatly described some parts of it are described in aicoe-ci documentation, but some are missing.
if you would like to add these details to documentation, we would happy with the contribution.

**Comment by martinpovolny** [comment]
Sure, @harshad16

**Comment by martinpovolny** [comment]
@SankBad : I want to double-check one thing in this issue: You want the notebook to be available on a generic ODH instance somewhere. 

You are NOT asking about having your notebook available in the existing ODH instance that we have in Red Hat -- the DH. Correct?

**Comment by harshad16** [comment]
If the question is regarding the notebook to be available in the existing internal ODH instance then this repository would be helpful https://github.com/thoth-station/jupyternb-build-pipeline.
we use the pipeline for internal setup, these pipelines build then image and use them in internal ODH instance.

**Comment by SankBad** [comment]
@martinpovolny , I want my notebook available on generic ODH instance which people outside Red hat can access. This notebook is already available on internal RedHat ODH.

**Comment by martinpovolny** [comment]
TODO: make sure that the information thah the builder image for jupyter notebook images is `s2i-custom-notebook`, https://github.com/AICoE/s2i-custom-notebook

**Comment by 4n4nd** [comment]
@SankBad This is an example [PR](https://github.com/operate-first/odh/pull/25) for adding new JH images

**Comment by SankBad** [comment]
Great! I will try this. I will let you know If I am facing any issues.

**Comment by SankBad** [comment]
Just an update my notebooks are now available on MOC JH :partying_face:

**Comment by 4n4nd** [comment]
I will add some documentation for:
* how to add a repo to the thoth build pipeline, maybe @harshad16 already has some docs.
* how to add the built image to the MOC Jupyterhub (creating an imagestream)

**Comment by harshad16** [comment]
@4n4nd  yes anand, i have some docs and i will update them in the operate-first/continous-delivery repository.
I m aiming to get everything there by this week.

**Comment by martinpovolny** [comment]
If you want to add your image to MOC, make a PR such as this one:
https://github.com/operate-first/odh/pull/25

If you need to add your image to the DH (ODH instance run by DH team),
make a PR against the `production` branch here:
https://github.com/AICoE/idh-manifests/blob/production/jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml

**Comment by SankBad** [comment]
This issue resolved. As we have a doc. 
Closing this issue. Thanks @martinpovolny
