### ISSUE TITLE
Where is the code for "http://www.operate-first.cloud/config-analysis/configuration-file-analysis-blog" ?

### ISSUE THREAD

**Issue by eranra** [operate-first/odh-moc-support#21]
**Description**

**Additional context**

**Comment by SankBad** [comment]
Hi @eranra ,

Code is currently on GitHub repo [URL](https://github.com/aicoe-aiops/configuration-files-analysis). 
I am in the process of making the notebook to moc [jupyterhub](https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/hub/login).

Let me know if you have any additional questions?

**Comment by durandom** [comment]
@SankBad can you add the URL to your blog post too? 
And let the PR reference this issue

**Comment by SankBad** [comment]
Hi @durandom , 

Github URL is in the blog. 
I need to change jupyterhub section. I am on it with the issue [link](https://github.com/operate-first/operate-first.github.io/issues/102)
