### ISSUE TITLE
web site http://www.operate-first.cloud/ is down ??? 

### ISSUE THREAD

**Issue by eranra** [operate-first/odh-moc-support#22]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/3080696/99633729-0bdd5a80-2a48-11eb-96ff-c5ebe7a97e22.png)

**Comment by oindrillac** [comment]
@eranra If you're trying to access the website, can you please try to visit https://operate-first.github.io/ instead, that should lead you to the same site.

I believe the address https://www.operate-first.cloud/ is currently down, will update once it's back up.

**Comment by eranra** [comment]
@oindrillac :-)
