### ISSUE TITLE
MOC JH gives similar names to every selected projects

### ISSUE THREAD

**Issue by SankBad** [operate-first/odh-moc-support#24]
**Is your feature request related to a problem? Please describe.**
Currently, we have different projects in MOC JH that we can select from the Spawn screen.

But, I select any of them, I get a generic name with the format `notebook-yyyy-mm-dd-hh-mm`
If I am working on multiple project's its really difficult to find the project I am interested in, In the following picture I opened four different projects but all of them have similar names. 
![image](https://user-images.githubusercontent.com/29823086/100239731-b994b180-2eff-11eb-8e3e-e23d6df45a79.png)

**Describe the solution you'd like**
You can give a name such as `project_name-yyyy-mm-dd-hh-mm`

**Comment by SankBad** [comment]
Different name feature exist in internal JH

**Comment by 4n4nd** [comment]
@SankBad This is something that needs to be changes in the build pipeline for JH images.
@harshad16 is already working on it I think ([issue](https://github.com/AICoE/aicoe-ci/issues/82))

**Comment by SankBad** [comment]
Great, I am closing this issue.

**Comment by 4n4nd** [comment]
This should be fixed by @harshad16 in [this PR.](https://github.com/AICoE/aicoe-ci/pull/84)
