### ISSUE TITLE
Request for kafka on operate-first

### ISSUE THREAD

**Issue by harshad16** [operate-first/odh-moc-support#27]
**Is your feature request related to a problem? Please describe.**
Thoth-station component uses Kafka messaging.It is a required component for the proper functioning of thoth-station system.
we would like to request Kafka setup on operate-first so that component can connect to it via SSL or SASL connection.

**Describe the solution you'd like**
Use amq-stream operator or strimzi operator to deploy a 2 kafka broker , 3 zookeeper node instance.

**Describe alternatives you've considered**
get the kafka via odh-operator

**Comment by harshad16** [comment]
Related-to: https://github.com/operate-first/odh/issues/10

**Comment by harshad16** [comment]
@HumairAK noticed you worked on the kafka deployment. 
Thanks for the docs to update the [kafkatopic](https://github.com/operate-first/odh/blob/master/docs/add_kafka_topics.md).
can you please also guide me how to get the:  Kafka broker URL + ca.cert  required for SSL connection ? 
so that we can start with thoth component deployment.

**Comment by HumairAK** [comment]
[related](https://github.com/operate-first/odh/pull/62)
