### ISSUE TITLE
Request access to Ceph storage on MOC

### ISSUE THREAD

**Issue by chauhankaranraj** [operate-first/odh-moc-support#31]
**Description**
Hey team, I wanted to upload some publicly available data that the notebooks in [openshift-anomaly-detection](https://github.com/aicoe-aiops/openshift-anomaly-detection) project will be using. Could I please get read-write access to an s3 bucket on MOC ceph?

**Additional context**
Related issues: #23, aicoe-aiops/openshift-anomaly-detection#3

cc @4n4nd

**Comment by 4n4nd** [comment]
@HumairAK Should we create a bucket in the `opf-Jupyterhub` namespace, since the data will mainly be accessed using JH notebook servers?

**Comment by 4n4nd** [comment]
The main requirement here is to be generate read-only keys for the bucket, which can be distributed to the public

**Comment by HumairAK** [comment]
Hrmm so as I understand it, this will be done via creating OBC's, which I think should be handled similar to PVC's, in which case I think it makes sense to keep our buckets with the namespaces containing the services for which they are meant for (opf-jupyterhub for this particular case). 

@tumido @durandom  @anishasthana  thoughts?

**Comment by tumido** [comment]
Sure you can do that! See the docs here:
Create additional user: https://rook.io/docs/rook/v1.5/ceph-object.html#create-a-user
This CRD should support setting Bucket Policy: https://github.com/rook/rook/blob/master/design/ceph/object/bucketpolicy.md

**Comment by HumairAK** [comment]
I've had a skim over that repo, I do not think they have implemented bucketpolicies (despite the target being 1.4 and current release being at 1.5). It's also not included in heir docs for OBC's.

**Comment by tumido** [comment]
I don't know. Maybe you're right. It's certainly missing from the docs on the community page. Yet the policies code seems available:
https://github.com/rook/rook/blob/release-1.4/pkg/operator/ceph/object/policy.go

I don't know. Why don't we just try it. And if it doesn't work, we can come up with a feature request (or voice our interest for the existing one) and work around it for now with some kind on demand bucket creation + syncing the data for the read user (so they can destroy their own bucket only)

**Comment by HumairAK** [comment]
yeah I'm good with trying it out @4n4nd  ^^

**Comment by durandom** [comment]
@chauhankaranraj what's the size and kind of the data and how is it being used?

Let's hold back any quick'n'dirty solutions, if we don't know what we actually want to achieve :) 
We can continue to discuss the requirements at #23

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj what's the size and kind of the data and how is it being used?
> 
> Let's hold back any quick'n'dirty solutions, if we don't know what we actually want to achieve :)
> We can continue to discuss the requirements at #23

The data is one day's worth of prometheus metrics collected from CI/CD clusters, stored as parquet files (roughly 10MB). It would be for using in the anomaly detection notebook (see aicoe-aiops/openshift-anomaly-detection#3)

**Comment by durandom** [comment]
Let's put it into git and the notebook image for now and wait until we have a better understanding how we git-ops PVC/OBC
