### ISSUE TITLE
Missing runtimes list in ODH Elyra

### ISSUE THREAD

**Issue by pacospace** [operate-first/odh-moc-support#8]
As Data Scientists,

when I run my Elyra image on ODH and try looking for available runtimes, I don't fin any available.

when I create an AI pipeline and try to assign one image to the step in the pipeline, there is a list of defaults runtimes.

This behaviour I think is a bit confusing. Using upstream image of Elyra from https://github.com/elyra-ai/elyra. This behaviour is not present.

On ODH Elyra I expect to have a list of runtimes available.

**Comment by pacospace** [comment]
This is a question actually, it might be because we use v1.0.0 of Elyra as part of ODH 0.8.0 on Operate first

**Comment by pacospace** [comment]
> This is a question actually, it might be because we use v1.0.0 of Elyra as part of ODH 0.8.0 on Operate first

I ll close it for now and in case reopen,I don't have this issue using Elyra v1.2.1 in elyra-lab-s2i:v0.0.4 from odh

**Comment by goern** [comment]
To shed some light on the release z topic i created https://github.com/opendatahub-io/odh-manifests/pull/224
